version: "3.7"

services:

  settings-tp:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  fashion-tp:
    build:
      context: ./fashion-tp
      dockerfile: Dockerfile
    container_name: sawtooth-fashion-tp
    depends_on:
      - validator
    entrypoint: fashion-tp -vv -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  fashion-client:
    build:
      context: ./fashion-client
      dockerfile: Dockerfile
    container_name: fashion-client
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
